

services:
  mysql:
    image: mysql:8.0
    container_name: wp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - wpnet

  wordpress-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: local/wordpress-fpm:8.2
    container_name: wp_fpm
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpnet
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - wpnet
    depends_on:
      - wordpress-fpm

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: wp_selenium
    restart: unless-stopped
    ports:
      - "4444:4444"
    networks:
      - wpnet
    user: "1000:1000"  # seluser UID:GID
    volumes:
      - ./wordpress/wp-content/plugins/rw-postviewstats-lite/tests/_output:/home/seluser/Downloads

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: wpuser
      PMA_PASSWORD: wppass
    ports:
      - "8081:80"
    networks:
      - wpnet


networks:
  wpnet:

volumes:
  db_data:
