name: RW PostViewStats Lite Codeception Tests

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # 使用 Docker Compose 方式
      docker:
        image: docker:24.0.5-dind
        options: --privileged
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
      WP_PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build PHP + WordPress image
        run: |
          docker build -t wp-test -f ci/Dockerfile .

      - name: Start all services
        run: |
          docker network create wp-net || true
          # 启动 MySQL
          docker run -d --name mysql --network wp-net \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=test_db \
            mysql:8.0
          # 启动 WordPress + PHP-FPM / Apache
          docker run -d --name wordpress --network wp-net \
            -p $WP_PORT:80 \
            -e WORDPRESS_DB_HOST=mysql:3306 \
            -e WORDPRESS_DB_USER=root \
            -e WORDPRESS_DB_PASSWORD=root \
            -e WORDPRESS_DB_NAME=test_db \
            -v ${{ github.workspace }}/wp:/var/www/html \
            wp-test
          # 启动 Selenium
          docker run -d --network wp-net --shm-size=2g --name selenium selenium/standalone-chrome:120.0

          # 等待 MySQL 和 WordPress 启动
          echo "Waiting for MySQL..."
          docker exec mysql sh -c 'until mysqladmin ping -uroot -proot --silent; do sleep 2; done'
          echo "Waiting for WordPress..."
          sleep 15

      - name: Install WordPress Core & Plugin
        run: |
          docker exec wordpress wp core install \
            --url="http://wordpress:80" \
            --title="Test Site" \
            --admin_user="$WP_ADMIN_USER" \
            --admin_password="$WP_ADMIN_PASS" \
            --admin_email="test@example.com" \
            --skip-email
          docker exec wordpress wp plugin activate rw-postviewstats-lite

      - name: Run Codeception tests
        run: |
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && vendor/bin/codecept run Unit"
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && vendor/bin/codecept run Integration"
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && vendor/bin/codecept run Acceptance ShortcodeCest.php"