name: RW PostViewStats Lite Codeception Tests

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
        wp: [6.8]

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        command: >
          --default-authentication-plugin=mysql_native_password

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444
        options: >-
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      WP_DB_HOST: mysql   # 用容器名 mysql，Actions 会解析
      WP_DB_NAME: test_db
      WP_DB_USER: root
      WP_DB_PASSWORD: root
      WP_DIR: ${{ github.workspace }}/wp
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444

    steps:
      - name: Test MySQL connection
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql -hmysql -uroot -proot -e "SHOW DATABASES;"