name: Test MySQL Only

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  mysql-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Test MySQL connection
        run: |
          echo "Databases on MySQL:"
          mysql -h127.0.0.1 -P3306 -uroot -proot -e "SHOW DATABASES;"

