name: RW PostViewStats Lite Codeception Tests

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  mysql-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
        wp: [6.8]

    services:

      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -s http://127.0.0.1:4444/wd/hub/status | grep -q '\"ready\":\s*true'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      WP_DB_HOST: 127.0.0.1
      WP_DB_NAME: test_db
      WP_DB_USER: root
      WP_DB_PASSWORD: root
      WP_DIR: ${{ github.workspace }}/wp
      SELENIUM_HOST: 127.0.0.1
      SELENIUM_PORT: 4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, mysqli
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Setup WordPress
        run: |
          wget https://wordpress.org/wordpress-${{ matrix.wp }}.tar.gz
          tar -xzf wordpress-${{ matrix.wp }}.tar.gz
          mv wordpress wp

      - name: Adjust Path
        run: |
          rm -f wordpress-6.8.tar.gz
          mv wp /home/runner/work/
          mkdir -p /home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite
          cp -R * /home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite/
          cd /home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite

      - name: Debug current directory
        run: |
          echo "Current path:"
          pwd
          echo "Files in current directory:"          
          ls -al
          
          echo "/home/runner/work/:"
          ls -al /home/runner/work/

          echo "/home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite/:"
          ls -al /home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite/
          
          echo "composer.json:"
          cat /home/runner/work/wp/wp-content/plugins/rw-postviewstats-lite/composer.json

#      - name: Move plugin into WordPress plugins folder
#        shell: bash
#        run: |
#          shopt -s extglob
#          mkdir -p wp/wp-content/plugins/rw-postviewstats-lite
#          cp -R !(wp) wp/wp-content/plugins/rw-postviewstats-lite/
#
#      - name: Make run-tests.sh executable
#        run: chmod +x wp/wp-content/plugins/rw-postviewstats-lite/run-tests.sh
#
#      - name: Run Codeception tests
#        run: |
#          cd wp/wp-content/plugins/rw-postviewstats-lite
#          ./run-tests.sh
