name: RW PostViewStats Lite Codeception Tests (docker-compose)

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
      WP_ADMIN_EMAIL: robert2021south@gmail.com
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      WP_PORT: 8080

    steps:
      # 1 检出代码
      - name: 1. Checkout code
        uses: actions/checkout@v3

      # 2. 创建临时插件目录
      - name: Prepare plugin directory
        run: |
          pwd
          ls -la ./
          mkdir -p docker/wordpress/wp-content/plugins/rw-postviewstats-lite
          rsync -a --exclude='docker' ./* docker/wordpress/wp-content/plugins/rw-postviewstats-lite/
          ls -la docker/wordpress/wp-content/plugins/rw-postviewstats-lite/


      # 3. 启动 Docker Compose 环境
      - name: Start Docker Compose
        run: |
          pwd
          docker compose version
          cd docker
          ls -la
          docker compose up -d --build
          docker ps

      # 4. 等待 WordPress/PHP-FPM/MySQL 就绪
      - name: Wait for services
        run: |
          echo "⏳ Waiting for MySQL and PHP-FPM to start..."
          sleep 30

      # 5. 安装 Composer（在容器内）
      - name: Install Composer inside wp_fpm container
        run: |
          docker exec wp_fpm bash -lc '\
            if [ ! -f /usr/local/bin/composer ]; then \
              curl -sS https://getcomposer.org/installer | php && \
              mv composer.phar /usr/local/bin/composer && \
              chmod +x /usr/local/bin/composer ; \
            fi
          '

      # 6. 在容器内安装插件依赖
      - name: Install plugin dependencies
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            composer install --no-interaction --prefer-dist --optimize-autoloader;
          '

      # 7. 安装 WordPress
      - name: Install WordPress
        run: |
          docker exec wp_fpm bash -lc '\
            wp core install \
              --url="http://wp_nginx/" \
              --title="Test Site" \
              --admin_user="$WP_ADMIN_USER" \
              --admin_password="$WP_ADMIN_PASS" \
              --admin_email="$WP_ADMIN_EMAIL" \
              --skip-email \
              --allow-root \
              --path=/var/www/html
          '

      # 8. 激活插件
      - name: Activate plugin
        run: |
          docker exec wp_fpm bash -lc '\
            wp plugin activate rw-postviewstats-lite \
              --allow-root \
              --path=/var/www/html
          '

      # 9. 运行 Unit 测试
      - name: Run Unit Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            ./vendor/bin/codecept build && \
            ./vendor/bin/codecept run Unit
          '

      # 10. 运行 Integration 测试
      - name: Run Integration Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            ./vendor/bin/codecept run Integration
          '

      # 11. 运行 Acceptance 测试
      - name: Run Acceptance Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            TEST_SELENIUM_HOST=wp_selenium TEST_SELENIUM_PORT=4444 \
            ./vendor/bin/codecept run Acceptance
          '