name: RW PostViewStats Lite Codeception Tests

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
      WP_PORT: 8080

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Docker network
        run: docker network create wp-net || true

      - name: Start WordPress container
        run: |
          docker run -d --name wordpress \
            --network wp-net \
            -p $WP_PORT:80 \
            -v ${{ github.workspace }}/wp:/var/www/html/wp-content/plugins/rw-postviewstats-lite \
            -e WORDPRESS_DB_HOST=mysql:3306 \
            -e WORDPRESS_DB_USER=root \
            -e WORDPRESS_DB_PASSWORD=root \
            -e WORDPRESS_DB_NAME=test_db \
            wordpress:6.8-php8.2-apache

      - name: Start Selenium container
        run: |
          docker run -d --name selenium \
            --network wp-net \
            -p 4444:4444 \
            -e SE_OPTS="-host 0.0.0.0" \
            selenium/standalone-chrome:120.0

      - name: Wait for services to be ready
        run: |
          echo "Waiting for MySQL..."
          docker exec mysql sh -c 'until mysqladmin ping -uroot -proot --silent; do sleep 2; done'
          echo "Waiting for WordPress..."
          sleep 20
          echo "Waiting for Selenium..."
          sleep 10

      - name: Install WordPress & Activate Plugin
        run: |
          docker exec wordpress wp core install \
            --url="http://wordpress:80" \
            --title="Test Site" \
            --admin_user="$WP_ADMIN_USER" \
            --admin_password="$WP_ADMIN_PASS" \
            --admin_email="test@example.com" \
            --skip-email
          docker exec wordpress wp plugin activate rw-postviewstats-lite

      - name: Run Codeception Unit & Integration tests
        run: |
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && vendor/bin/codecept run Unit"
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && vendor/bin/codecept run Integration"

      - name: Run Codeception Acceptance tests
        run: |
          docker exec wordpress bash -c "cd wp-content/plugins/rw-postviewstats-lite && \
            TEST_SELENIUM_HOST=selenium TEST_SELENIUM_PORT=4444 vendor/bin/codecept run Acceptance"
