name: RW PostViewStats Lite Codeception Tests

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
        wp: [6.8]

    services:

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -s http://127.0.0.1:4444/wd/hub/status | grep -q '\"ready\":\s*true'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      WP_DB_HOST: 127.0.0.1
      WP_DB_PORT: 3306
      WP_DB_NAME: test_db
      WP_DB_USER: root
      WP_DB_PASS: root
      WP_DB_TABLE_PREFIX: wp_

      SELENIUM_HOST: 127.0.0.1
      SELENIUM_PORT: 4444

      WP_DOMAIN: rwpsl.local
      WP_URL: http://rwpsl.local
      WP_DIR: ${{ github.workspace }}/wp  #${{ github.workspace }}值为 /home/runner/work/rw-postviewstats-lite/rw-postviewstats-lite
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}

    steps:
      - name: Check MySQL service
        run: echo "MySQL service is running"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl, mysqli
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Install WP-CLI
        run: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            php wp-cli.phar --info
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
            wp --info

      - name: Setup WordPress
        run: |
          wget https://wordpress.org/wordpress-${{ matrix.wp }}.tar.gz
          tar -xzf wordpress-${{ matrix.wp }}.tar.gz
          mv wordpress wp

      - name: Move Plugin Files
        run: |
          rm -f wordpress-*.tar.gz
          mkdir -p wp/wp-content/plugins/rw-postviewstats-lite
          shopt -s extglob
          mv !(wp) wp/wp-content/plugins/rw-postviewstats-lite
          ls -la wp/wp-content/plugins/


      - name: Configure WordPress
        run: |
          cd wp
          cp wp-config-sample.php wp-config.php
      
          # 替换数据库配置
          sed -i "s/database_name_here/test_db/g" wp-config.php
          sed -i "s/username_here/root/g" wp-config.php
          sed -i "s/password_here/root/g" wp-config.php
          sed -i "s/localhost/127.0.0.1:3306/g" wp-config.php
      
          # 删除旧的 AUTH_KEY/盐值定义，避免重复
          sed -i "/AUTH_KEY/d" wp-config.php
          sed -i "/SECURE_AUTH_KEY/d" wp-config.php
          sed -i "/LOGGED_IN_KEY/d" wp-config.php
          sed -i "/NONCE_KEY/d" wp-config.php
          sed -i "/AUTH_SALT/d" wp-config.php
          sed -i "/SECURE_AUTH_SALT/d" wp-config.php
          sed -i "/LOGGED_IN_SALT/d" wp-config.php
          sed -i "/NONCE_SALT/d" wp-config.php
      
          # 插入新的盐值
          curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> wp-config.php
      
          # 添加测试环境相关配置
          echo "" >> wp-config.php
          echo "// 测试环境配置" >> wp-config.php
          # 修改 WP_DEBUG
          sed -i "s/define( 'WP_DEBUG', false );/define( 'WP_DEBUG', true );/" wp-config.php
          
          # 如果没定义 WP_DEBUG_LOG，就插入一行
          grep -q "WP_DEBUG_LOG" wp-config.php || \
          sed -i "/define( 'WP_DEBUG', true );/a define( 'WP_DEBUG_LOG', true );" wp-config.php
            
          # 添加其他测试环境配置
          grep -q "WP_ENVIRONMENT_TYPE" wp-config.php || echo "define('WP_ENVIRONMENT_TYPE', 'testing');" >> wp-config.php
          grep -q "TEST_SITE_URL" wp-config.php || echo "define('TEST_SITE_URL', 'http://127.0.0.1');" >> wp-config.php        

      - name: Install WordPress
        run: |
          cd wp
          wp core install \
            --url="http://127.0.0.1" \
            --title="Test Site" \
            --admin_user="admin" \
            --admin_password="pBlaWDphJvFab5Jbi3KR9q6s" \
            --admin_email="robert2021south@gmail.com" \
            --skip-email

      - name: Start Selenium Server
        run: |
            nohup java -jar selenium-server.jar standalone > selenium.log 2>&1 &

      - name: Detect runner IP
        run: echo "RUNNER_IP=$(hostname -I | awk '{print $1}')" >> $GITHUB_ENV

      - name: Run Codeception tests
        working-directory: wp/wp-content/plugins/rw-postviewstats-lite
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh