name: RW PostViewStats Lite Codeception Tests (docker-compose)

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      WP_ADMIN_USER: ${{ secrets.WP_ADMIN_USER }}
      WP_ADMIN_PASS: ${{ secrets.WP_ADMIN_PASS }}
      WP_ADMIN_EMAIL: robert2021south@gmail.com

      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: rootpass
      WP_PORT: 8080

    steps:
      # 检出代码
      - name: 1. Checkout code
        uses: actions/checkout@v3

      # 创建临时插件目录
      - name: 2. Prepare plugin directory
        run: |
          mkdir -p docker/wordpress/wp-content/plugins/rw-postviewstats-lite
          rsync -a --exclude='docker' ./* docker/wordpress/wp-content/plugins/rw-postviewstats-lite/
          chmod -R 777 docker/wordpress/wp-content/plugins/rw-postviewstats-lite/tests/_output

      # 启动 Docker Compose 环境
      - name: 3. Start Docker Compose
        run: |
          cd docker
          docker compose up -d --build
          docker ps

      # 等待 WordPress/PHP-FPM/MySQL 就绪
      - name: 4. Wait for services
        run: |
          echo "⏳ Waiting for MySQL and PHP-FPM to start..."
          sleep 10

      # 在容器内安装插件依赖
      - name: 5. Install plugin dependencies
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            composer install --no-interaction --prefer-dist --optimize-autoloader;
          '
      # 安装 WP-CLI
      - name: 6. Install WP-CLI inside wp_fpm container
        run: |
          docker exec wp_fpm bash -c '
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&
            chmod +x wp-cli.phar &&
            mv wp-cli.phar /usr/local/bin/wp
          '

      # 安装 WordPress && 激活插件
      - name: 7. Install WordPress && Activate plugin
        run: |
          docker exec wp_fpm bash -lc "\
          wp core install \
          --url='http://nginx/' \
          --title='Test Site' \
          --admin_user='$WP_ADMIN_USER' \
          --admin_password='$WP_ADMIN_PASS' \
          --admin_email='$WP_ADMIN_EMAIL' \
          --skip-email \
          --allow-root \
          --path=/var/www/html
          "

          docker exec wp_fpm bash -lc '\
            wp plugin activate rw-postviewstats-lite --allow-root --path=/var/www/html
          '

      # 运行 Unit 测试
      - name: 8. Run Unit Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            ./vendor/bin/codecept run Unit
          '

      # 运行 Integration 测试
      - name: 9. Run Integration Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            ./vendor/bin/codecept run Integration
          '

      # 运行 Acceptance 测试
      - name: 10. Run Acceptance Tests
        run: |
          docker exec wp_fpm bash -lc '\
            cd /var/www/html/wp-content/plugins/rw-postviewstats-lite && \
            TEST_SELENIUM_HOST=wp_selenium TEST_SELENIUM_PORT=4444 \
            ./vendor/bin/codecept run Acceptance
          '
