name: Test Selenium Only

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  mysql-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep -q '\"ready\":\s*true'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Verify Selenium
        run: |
          echo "Checking Selenium status..."
          until curl -s http://selenium:4444/wd/hub/status | grep -q '"ready":true'; do
            echo "Selenium not ready yet..."
            sleep 2
          done
          echo "Selenium is ready!"

